# Name of your application
service: ighana

# Name of the container image
image: kojb/ighana

# Deploy to these servers
servers:
  web:
    - 78.47.104.216

# Proxy settings
proxy:
  ssl: false
  host: imlikeu.com

registry:
  username: kojb
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    RAILS_LOG_LEVEL: debug
    PORT: 80
    BIND: "tcp://0.0.0.0:80"

volumes:
  - "i_ghana_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: arm64